
project_id = "nnlxxbuekqlaqamczwyi"

[functions.mpesa]
verify_jwt = true

[functions.mpesa-callback]
verify_jwt = false

[functions.process-ghost-actions]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false
