-- Seed Sample Events Data
-- This migration adds sample events with performing artists and times for testing

-- Insert sample events
INSERT INTO public.events (
  title,
  description,
  category,
  date,
  time,
  location,
  image_url,
  price,
  capacity,
  featured,
  tags,
  performing_artists,
  organizer_id
) VALUES
(
  'Nairobi Music Festival 2025',
  'Join us for the biggest music festival in Nairobi featuring top Kenyan artists and international acts. Experience live performances, food vendors, and an unforgettable atmosphere.',
  'Music',
  (CURRENT_DATE + INTERVAL '7 days')::timestamp with time zone,
  '18:00:00',
  'Kasarani Stadium, Nairobi',
  'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=2070',
  2500,
  5000,
  true,
  ARRAY['music', 'festival', 'live', 'nairobi'],
  ARRAY['Sauti Sol', 'Wakadinali', 'Nadia Mukami', 'Nyashinski'],
  NULL
),
(
  'Tech Innovation Summit',
  'A gathering of tech enthusiasts, entrepreneurs, and innovators. Network, learn, and discover the latest trends in technology.',
  'Technology',
  (CURRENT_DATE + INTERVAL '10 days')::timestamp with time zone,
  '09:00:00',
  'Sarit Centre, Westlands, Nairobi',
  'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072',
  1500,
  300,
  true,
  ARRAY['tech', 'innovation', 'networking', 'startups'],
  ARRAY['Tech Leaders Panel', 'Startup Founders'],
  NULL
),
(
  'Mombasa Food & Culture Festival',
  'Experience the rich culinary traditions of the Kenyan coast. Taste authentic Swahili dishes, enjoy traditional music and dance performances.',
  'Food',
  (CURRENT_DATE + INTERVAL '14 days')::timestamp with time zone,
  '12:00:00',
  'Fort Jesus, Mombasa',
  'https://images.unsplash.com/photo-1529154045759-34c09aed3b73?q=80&w=2070',
  800,
  1000,
  true,
  ARRAY['food', 'culture', 'mombasa', 'swahili'],
  ARRAY['Coastal Chefs', 'Taarab Musicians', 'Traditional Dancers'],
  NULL
),
(
  'Nairobi Marathon 2025',
  'Join thousands of runners for the annual Nairobi Marathon. Choose from full marathon, half marathon, or 10K routes.',
  'Sports',
  (CURRENT_DATE + INTERVAL '21 days')::timestamp with time zone,
  '06:00:00',
  'Nyayo National Stadium, Nairobi',
  'https://images.unsplash.com/photo-1474224017046-182ece80b263?q=80&w=2070',
  2000,
  10000,
  false,
  ARRAY['sports', 'marathon', 'running', 'fitness'],
  ARRAY['Elite Runners', 'Fitness Coaches'],
  NULL
),
(
  'Art & Design Exhibition',
  'Contemporary art exhibition featuring works from emerging and established Kenyan artists. Includes live painting sessions and artist talks.',
  'Culture',
  (CURRENT_DATE + INTERVAL '5 days')::timestamp with time zone,
  '14:00:00',
  'Nairobi National Museum, Nairobi',
  'https://images.unsplash.com/photo-1541961017774-22349e4a1262?q=80&w=2070',
  500,
  200,
  false,
  ARRAY['art', 'design', 'exhibition', 'culture'],
  ARRAY['Local Artists', 'Guest Curators'],
  NULL
),
(
  'Jazz Night at The Alchemist',
  'An intimate evening of smooth jazz featuring Nairobi''s finest jazz musicians. Enjoy cocktails and great music in a relaxed atmosphere.',
  'Music',
  (CURRENT_DATE + INTERVAL '3 days')::timestamp with time zone,
  '20:00:00',
  'The Alchemist Bar, Westlands, Nairobi',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=2070',
  1500,
  150,
  false,
  ARRAY['jazz', 'music', 'nightlife', 'westlands'],
  ARRAY['Jazz Collective', 'Solo Pianist'],
  NULL
),
(
  'Business Networking Mixer',
  'Connect with entrepreneurs, investors, and business leaders. Perfect for startups looking to expand their network.',
  'Business',
  (CURRENT_DATE + INTERVAL '12 days')::timestamp with time zone,
  '17:30:00',
  'Radisson Blu Hotel, Upper Hill, Nairobi',
  'https://images.unsplash.com/photo-1676372971824-ed498ef0db5f?q=80&w=2070',
  2000,
  250,
  false,
  ARRAY['business', 'networking', 'startups', 'investment'],
  ARRAY['Keynote Speakers', 'Investor Panel'],
  NULL
),
(
  'Comedy Night Live',
  'Laugh your heart out with Kenya''s funniest comedians. An evening of stand-up comedy guaranteed to leave you in stitches.',
  'Entertainment',
  (CURRENT_DATE + INTERVAL '8 days')::timestamp with time zone,
  '19:30:00',
  'Comedy Central, Kilimani, Nairobi',
  'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2070',
  1200,
  300,
  false,
  ARRAY['comedy', 'entertainment', 'stand-up', 'laughter'],
  ARRAY['Top Comedians', 'Guest Performers'],
  NULL
),
(
  'Yoga & Wellness Retreat',
  'A day of relaxation and rejuvenation. Includes yoga sessions, meditation, healthy meals, and wellness workshops.',
  'Health & Wellness',
  (CURRENT_DATE + INTERVAL '15 days')::timestamp with time zone,
  '08:00:00',
  'Karura Forest, Nairobi',
  'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=2070',
  3000,
  50,
  false,
  ARRAY['yoga', 'wellness', 'meditation', 'retreat'],
  ARRAY['Certified Yoga Instructors', 'Wellness Coaches'],
  NULL
),
(
  'Gaming Tournament',
  'Compete in the biggest gaming tournament in Kenya. Multiple game categories including FIFA, Call of Duty, and more.',
  'Gaming',
  (CURRENT_DATE + INTERVAL '18 days')::timestamp with time zone,
  '10:00:00',
  'Gaming Hub, Yaya Centre, Nairobi',
  'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=2070',
  1000,
  200,
  false,
  ARRAY['gaming', 'esports', 'tournament', 'competition'],
  ARRAY['Pro Gamers', 'Commentators'],
  NULL
)
ON CONFLICT DO NOTHING;

-- Add comment
COMMENT ON TABLE public.events IS 'Events table with performing artists and time support';

