-- Peer ticket gifts / transfers (claim + reject)
CREATE TABLE IF NOT EXISTS public.ticket_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id bigint NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  transfer_type text NOT NULL DEFAULT 'gift'
    CHECK (transfer_type IN ('gift', 'direct')),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
  message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ticket_transfers_recipient_status_idx
  ON public.ticket_transfers (recipient_id, status);
CREATE INDEX IF NOT EXISTS ticket_transfers_sender_idx
  ON public.ticket_transfers (sender_id);
CREATE INDEX IF NOT EXISTS ticket_transfers_ticket_idx
  ON public.ticket_transfers (ticket_id);

ALTER TABLE public.ticket_transfers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ticket_transfers_select_own ON public.ticket_transfers;
CREATE POLICY ticket_transfers_select_own
  ON public.ticket_transfers FOR SELECT TO authenticated
  USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

DROP POLICY IF EXISTS ticket_transfers_insert_sender ON public.ticket_transfers;
CREATE POLICY ticket_transfers_insert_sender
  ON public.ticket_transfers FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS ticket_transfers_update_parties ON public.ticket_transfers;
CREATE POLICY ticket_transfers_update_parties
  ON public.ticket_transfers FOR UPDATE TO authenticated
  USING (auth.uid() = sender_id OR auth.uid() = recipient_id)
  WITH CHECK (auth.uid() = sender_id OR auth.uid() = recipient_id);

COMMENT ON TABLE public.ticket_transfers IS 'Direct / gift ticket transfers between users';
