import type { Event } from '@/types/event.types';

export type SeededSponsor = {
  name: string;
  type: string;
  logo: string;
  /** Figma brand card styles */
  cardClass: string;
  nameClass: string;
  typeClass: string;
  logoClass: string;
};

/** Figma 15 — Concept D seeded events (use until live feed is wired). */
export type SeededEvent = Event & {
  subtitle?: string;
  dateLabel: string;
  timeLabel?: string;
  ticketLabel: string;
  expect?: string[];
  organizerName?: string;
  organizerMeta?: string;
  sponsors?: SeededSponsor[];
  going?: number;
  interested?: number;
};

export const FIGMA_SPONSORS: SeededSponsor[] = [
  {
    name: 'Safaricom',
    type: 'Title sponsor',
    logo: '/events/sponsors/safaricom.png',
    cardClass: 'border-[1.5px] border-[#43b02a] bg-white',
    nameClass: 'text-[#0d1117]',
    typeClass: 'text-[#656d76]',
    logoClass: 'h-11 w-auto max-w-[132px] object-contain',
  },
  {
    name: 'Tusker',
    type: 'Beverage partner',
    logo: '/events/sponsors/tusker.png',
    cardClass: 'bg-[#fdb913]',
    nameClass: 'text-[#0d1117]',
    typeClass: 'text-[#3d3200]',
    logoClass: 'size-14 rounded-xl object-contain',
  },
  {
    name: 'Bolt',
    type: 'Mobility partner',
    logo: '/events/sponsors/bolt.png',
    cardClass: 'border-[1.5px] border-[#34d781] bg-black',
    nameClass: 'text-white',
    typeClass: 'text-[#34d781]',
    logoClass: 'size-[52px] rounded-full object-contain',
  },
];

export const FIGMA_SEEDED_EVENTS: SeededEvent[] = [
  {
    id: 9001,
    title: 'Afrobeat Fridays',
    description:
      'Afrobeat Fridays is Westlands’ weekly celebration of African sounds — live band, guest DJs, and a dancefloor that doesn’t quit. Expect high-energy sets, food stalls on the terrace, and a sunset golden-hour open.',
    category: 'Music',
    date: '2026-07-25',
    time: '21:00:00',
    location: 'The Alchemist Rooftop, Westlands, Nairobi',
    latitude: -1.2675,
    longitude: 36.8110,
    image_url: '/events/popup-cover.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 1500,
    featured: true,
    tags: ['Afrobeat', 'Live band', 'Rooftop', '18+', 'Nairobi nights'],
    subtitle: 'Westlands · Live music · Ages 18+',
    dateLabel: 'Fri · 25 Jul',
    timeLabel: 'Friday, 25 Jul 2026 · 9:00 PM – 2:00 AM',
    ticketLabel: 'KES 1,500',
    expect: [
      'Live Afrobeat band + rotating DJ guests',
      'Rooftop terrace with city views',
      'Food & drink vendors on site (cashless preferred)',
      'Dress code: smart casual · doors open 8:30 PM',
    ],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 186,
    interested: 42,
  },
  {
    id: 9002,
    title: 'Rooftop Jazz Sessions',
    description:
      'An intimate evening of live jazz above the city — vinyl warmups, a resident trio, and cocktail service under the stars.',
    category: 'Music',
    date: '2026-07-26',
    time: '19:00:00',
    location: 'Kilimani, Nairobi',
    latitude: -1.2884,
    longitude: 36.7855,
    image_url: '/events/vibe-jazz.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 2000,
    featured: false,
    tags: ['Jazz', 'Rooftop', 'Live band'],
    subtitle: 'Kilimani · Jazz · Ages 18+',
    dateLabel: 'Sat · 26 Jul',
    timeLabel: 'Saturday, 26 Jul 2026 · 7:00 PM – 11:00 PM',
    ticketLabel: 'KES 2,000',
    expect: ['Live jazz trio', 'Skyline views', 'Craft cocktails'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 92,
    interested: 31,
  },
  {
    id: 9003,
    title: 'Night Market Feast',
    description:
      'Street food stalls, live DJs, and late-night bites across Nairobi CBD. Free entry — come hungry.',
    category: 'Food',
    date: '2026-07-27',
    time: '17:00:00',
    location: 'Nairobi CBD',
    latitude: -1.2864,
    longitude: 36.8172,
    image_url: '/events/vibe-food.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 0,
    featured: false,
    tags: ['Food', 'Market', 'Family'],
    subtitle: 'Nairobi CBD · Food · All ages',
    dateLabel: 'Sun · 27 Jul',
    timeLabel: 'Sunday, 27 Jul 2026 · 5:00 PM – 11:00 PM',
    ticketLabel: 'Free',
    expect: ['Street food vendors', 'Live DJ sets', 'Family-friendly'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 240,
    interested: 88,
  },
  {
    id: 9004,
    title: 'Warehouse Techno',
    description:
      'Industrial Area goes dark for a night of techno — warehouse acoustics, immersive lights, and a stacked DJ bill.',
    category: 'Nightlife',
    date: '2026-07-26',
    time: '22:00:00',
    location: 'Industrial Area, Nairobi',
    latitude: -1.3185,
    longitude: 36.8680,
    image_url: '/events/vibe-nightlife.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 2500,
    featured: true,
    tags: ['Techno', 'Nightlife', '18+'],
    subtitle: 'Industrial Area · Nightlife · Ages 18+',
    dateLabel: 'Sat · 26 Jul',
    timeLabel: 'Saturday, 26 Jul 2026 · 10:00 PM – 5:00 AM',
    ticketLabel: 'KES 2,500',
    expect: ['Warehouse sound system', 'Guest international DJs', 'Immersive lighting'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 310,
    interested: 120,
  },
  {
    id: 9005,
    title: 'Karen Art Walk',
    description:
      'Galleries, open studios, and outdoor installations across Karen — a weekend stroll for art lovers.',
    category: 'Arts',
    date: '2026-08-02',
    time: '10:00:00',
    location: 'Karen, Nairobi',
    latitude: -1.3197,
    longitude: 36.7085,
    image_url: '/events/vibe-arts.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 800,
    featured: false,
    tags: ['Arts', 'Walk', 'Culture'],
    subtitle: 'Karen · Arts · All ages',
    dateLabel: 'Sat · 2 Aug',
    timeLabel: 'Saturday, 2 Aug 2026 · 10:00 AM – 5:00 PM',
    ticketLabel: 'KES 800',
    expect: ['Gallery hops', 'Open studios', 'Local makers'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 64,
    interested: 22,
  },
  {
    id: 9006,
    title: 'Laugh Lab Comedy',
    description:
      'Stand-up showcase in Lavington — fresh faces, resident MCs, and a room that laughs loud.',
    category: 'Comedy',
    date: '2026-07-24',
    time: '20:00:00',
    location: 'Lavington, Nairobi',
    latitude: -1.2780,
    longitude: 36.7685,
    image_url: '/events/vibe-comedy.png',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 1200,
    featured: false,
    tags: ['Comedy', 'Stand-up', '18+'],
    subtitle: 'Lavington · Comedy · Ages 18+',
    dateLabel: 'Thu · 24 Jul',
    timeLabel: 'Thursday, 24 Jul 2026 · 8:00 PM – 10:30 PM',
    ticketLabel: 'KES 1,200',
    expect: ['Openers + headliner', 'Cash bar', 'Doors 7:30 PM'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 110,
    interested: 45,
  },
  {
    id: 9007,
    title: 'Sunrise Run Club',
    description:
      '5K social run through Uhuru Park at dawn — all paces welcome, then coffee with the crew.',
    category: 'Sports',
    date: '2026-07-26',
    time: '06:30:00',
    location: 'Uhuru Park, Nairobi',
    latitude: -1.2895,
    longitude: 36.8155,
    image_url: '/events/vibe-sports.jpg',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 0,
    featured: false,
    tags: ['Sports', 'Running', 'Outdoor'],
    subtitle: 'Uhuru Park · Sports · All ages',
    dateLabel: 'Sat · 26 Jul',
    timeLabel: 'Saturday, 26 Jul 2026 · 6:30 AM – 8:00 AM',
    ticketLabel: 'Free',
    expect: ['Guided 5K loop', 'All paces welcome', 'Post-run coffee meetup'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 78,
    interested: 34,
  },
  {
    id: 9008,
    title: 'Karura Sunset Yoga',
    description:
      'Flow under the canopy as the light softens — mats provided, beginners welcome, bring water.',
    category: 'Wellness',
    date: '2026-07-27',
    time: '17:30:00',
    location: 'Karura Forest, Nairobi',
    latitude: -1.2445,
    longitude: 36.8335,
    image_url: '/events/vibe-wellness.jpg',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 1000,
    featured: false,
    tags: ['Wellness', 'Yoga', 'Outdoor'],
    subtitle: 'Karura · Wellness · All ages',
    dateLabel: 'Sun · 27 Jul',
    timeLabel: 'Sunday, 27 Jul 2026 · 5:30 PM – 7:00 PM',
    ticketLabel: 'KES 1,000',
    expect: ['60-min guided flow', 'Mats available', 'Forest setting at golden hour'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 56,
    interested: 29,
  },
  {
    id: 9009,
    title: 'Nairobi Builders Night',
    description:
      'Founders, designers, and engineers swap demos over pizza — lightning talks, then open networking.',
    category: 'Tech',
    date: '2026-07-29',
    time: '18:30:00',
    location: 'iHub, Nairobi',
    latitude: -1.2890,
    longitude: 36.7825,
    image_url: '/events/vibe-tech.jpg',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 500,
    featured: false,
    tags: ['Tech', 'Meetup', 'Networking'],
    subtitle: 'iHub · Tech · Ages 18+',
    dateLabel: 'Tue · 29 Jul',
    timeLabel: 'Tuesday, 29 Jul 2026 · 6:30 PM – 9:00 PM',
    ticketLabel: 'KES 500',
    expect: ['Lightning demos', 'Open networking', 'Pizza & soft drinks'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 142,
    interested: 67,
  },
  {
    id: 9010,
    title: 'Maasai Market Pop-up',
    description:
      'Weekend craft market with jewelry, textiles, and street snacks — free entry, bring cash for vendors.',
    category: 'Markets',
    date: '2026-08-01',
    time: '10:00:00',
    location: 'Village Market, Nairobi',
    latitude: -1.2285,
    longitude: 36.8045,
    image_url: '/events/vibe-markets.jpg',
    organizer_id: 'seed-organizer',
    created_at: '2026-07-01T00:00:00Z',
    price: 0,
    featured: false,
    tags: ['Markets', 'Crafts', 'Family'],
    subtitle: 'Village Market · Markets · All ages',
    dateLabel: 'Sat · 1 Aug',
    timeLabel: 'Saturday, 1 Aug 2026 · 10:00 AM – 6:00 PM',
    ticketLabel: 'Free',
    expect: ['Local artisans', 'Street snacks', 'Family-friendly browsing'],
    organizerName: 'Glow Collective KE',
    organizerMeta: 'Verified organizer · 24 events hosted',
    sponsors: FIGMA_SPONSORS,
    going: 198,
    interested: 71,
  },
];

/** Figma Category rail — horizontal carousel (10 vibes for scroll). */
export const FIGMA_VIBE_COUNTS: { key: string; count: number; image: string }[] = [
  { key: 'Music', count: 42, image: '/events/vibe-music.png' },
  { key: 'Nightlife', count: 28, image: '/events/vibe-nightlife.png' },
  { key: 'Food', count: 19, image: '/events/vibe-food.png' },
  { key: 'Arts', count: 15, image: '/events/vibe-arts.png' },
  { key: 'Comedy', count: 11, image: '/events/vibe-comedy.png' },
  { key: 'Jazz', count: 9, image: '/events/vibe-jazz.png' },
  { key: 'Sports', count: 14, image: '/events/vibe-sports.jpg' },
  { key: 'Wellness', count: 12, image: '/events/vibe-wellness.jpg' },
  { key: 'Tech', count: 10, image: '/events/vibe-tech.jpg' },
  { key: 'Markets', count: 8, image: '/events/vibe-markets.jpg' },
];

export function getSeededEvent(id: number): SeededEvent | undefined {
  return FIGMA_SEEDED_EVENTS.find((e) => e.id === id);
}
